### ISSUE TITLE
Does this even work?

### ISSUE THREAD

**Issue by muhammedjenos** [storyblok/storyblok-csv-import-example#1]
The syntax is deprecated.
fromStream has been changed to parseStream.
Even then, i get the below error
Error: ENOENT: no such file or directory, open "data.csv"

The file is very much in the same directory though.
Any help?

**Comment by ademarCardoso** [comment]
Hi @muhammedjenos thank you to submited this issue, sorry for the delay in answering you. In the example, the name of the **.csv** file is like `demo.csv`, and it is imported into the code as [demo.csv](https://github.com/storyblok/storyblok-csv-import-example/blob/master/index.js#L15), did you change the file name in the code?
